spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mtg_db
    username: yann
    password: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

cardmarket:
  api:
    base-url: https://api.cardmarket.com
    app-token: ${CARDMARKET_APP_TOKEN:default_app_token}
    app-secret: ${CARDMARKET_APP_SECRET:default_app_secret}
    access-token: ${CARDMARKET_ACCESS_TOKEN:default_access_token}
    access-token-secret: ${CARDMARKET_ACCESS_TOKEN_SECRET:default_access_token_secret}