spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mtg_db
    username: yann
    password: postgresql
    driver-class-name: org.postgresql.Driver
  messages:
    basename: messages/messages
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8081